// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type V1RegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/validators.ts')['createUserValidator']>>
  response: MakeTuyauResponse<import('../app/modules/users/controllers/users_controller.ts').default['createUser'], true>
}
type V1SigninPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/users/controllers/users_controller.ts').default['login'], false>
}
type V1SignoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/modules/users/controllers/users_controller.ts').default['logout'], false>
}
export interface ApiDefinition {
  'v1': {
    'register': {
      '$url': {
      };
      '$post': V1RegisterPost;
    };
    'signin': {
      '$url': {
      };
      '$post': V1SigninPost;
    };
    'signout': {
      '$url': {
      };
      '$post': V1SignoutPost;
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
