// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeNonSerializedTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type V1SignupPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/validators.ts')['createUserValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/modules/users/controllers/users_controller.ts').default['createUser'], true>
}
type V1SigninPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/validators.ts')['loginUserValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/modules/users/controllers/users_controller.ts').default['login'], true>
}
type V1VerifyemailPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/users/validators.ts')['verifyEmailValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/modules/users/controllers/users_controller.ts').default['sendVerificationCode'], true>
}
type V1SignoutPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/modules/users/controllers/users_controller.ts').default['logout'], false>
}
type V1CheckGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/modules/users/controllers/users_controller.ts').default['check'], false>
}
type V1LumensGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/modules/lumens/controllers/lumens_controller.ts').default['getLumen'], false>
}
type V1LumensCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/lumens/validators/server.ts')['createLumenValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/modules/lumens/controllers/lumens_controller.ts').default['createLumen'], true>
}
type V1ArtifactsGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/modules/artifacts/controllers/artifacts_controller.ts').default['getArtifacts'], false>
}
type V1ArtifactsCreatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/modules/artifacts/validators/server.ts')['createArtifactValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/modules/artifacts/controllers/artifacts_controller.ts').default['createArtifact'], true>
}
export interface ApiDefinition {
  'v1': {
    'signup': {
      '$url': {
      };
      '$post': V1SignupPost;
    };
    'signin': {
      '$url': {
      };
      '$post': V1SigninPost;
    };
    'verify-email': {
      '$url': {
      };
      '$post': V1VerifyemailPost;
    };
    'signout': {
      '$url': {
      };
      '$post': V1SignoutPost;
    };
    'check': {
      '$url': {
      };
      '$get': V1CheckGetHead;
      '$head': V1CheckGetHead;
    };
    'lumens': {
      '$url': {
      };
      '$get': V1LumensGetHead;
      '$head': V1LumensGetHead;
      'create': {
        '$url': {
        };
        '$post': V1LumensCreatePost;
      };
    };
    'artifacts': {
      '$url': {
      };
      '$get': V1ArtifactsGetHead;
      '$head': V1ArtifactsGetHead;
      'create': {
        '$url': {
        };
        '$post': V1ArtifactsCreatePost;
      };
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
